//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloSoapClient.MyServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cityinfo", Namespace="http://localhost/")]
    [System.SerializableAttribute()]
    public partial class cityinfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codeField;
        
        private int populationField;
        
        private int areaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int population {
            get {
                return this.populationField;
            }
            set {
                if ((this.populationField.Equals(value) != true)) {
                    this.populationField = value;
                    this.RaisePropertyChanged("population");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int area {
            get {
                return this.areaField;
            }
            set {
                if ((this.areaField.Equals(value) != true)) {
                    this.areaField = value;
                    this.RaisePropertyChanged("area");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="MyServiceReference.MyServicePortType")]
    public interface MyServicePortType {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (HelloWorld_Request) сообщения HelloWorldRequest не соответствует значению по умолчанию (HelloWorld).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HelloSoapClient.MyServiceReference.HelloWorldResponse HelloWorld(HelloSoapClient.MyServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloSoapClient.MyServiceReference.HelloWorldResponse> HelloWorldAsync(HelloSoapClient.MyServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (GreetUser_Request) сообщения GreetUserRequest не соответствует значению по умолчанию (GreetUser).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HelloSoapClient.MyServiceReference.GreetUserResponse GreetUser(HelloSoapClient.MyServiceReference.GreetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloSoapClient.MyServiceReference.GreetUserResponse> GreetUserAsync(HelloSoapClient.MyServiceReference.GreetUserRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (GetCityInfo_Request) сообщения GetCityInfoRequest не соответствует значению по умолчанию (GetCityInfo).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HelloSoapClient.MyServiceReference.GetCityInfoResponse GetCityInfo(HelloSoapClient.MyServiceReference.GetCityInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloSoapClient.MyServiceReference.GetCityInfoResponse> GetCityInfoAsync(HelloSoapClient.MyServiceReference.GetCityInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class HelloWorldRequest {
        
        public HelloWorldRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string answer;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(string answer) {
            this.answer = answer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GreetUser_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class GreetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=1)]
        public int age;
        
        public GreetUserRequest() {
        }
        
        public GreetUserRequest(string name, int age) {
            this.name = name;
            this.age = age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GreetUser_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class GreetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string answer;
        
        public GreetUserResponse() {
        }
        
        public GreetUserResponse(string answer) {
            this.answer = answer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCityInfo_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class GetCityInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string name;
        
        public GetCityInfoRequest() {
        }
        
        public GetCityInfoRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCityInfo_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class GetCityInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public HelloSoapClient.MyServiceReference.cityinfo answer;
        
        public GetCityInfoResponse() {
        }
        
        public GetCityInfoResponse(HelloSoapClient.MyServiceReference.cityinfo answer) {
            this.answer = answer;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServicePortTypeChannel : HelloSoapClient.MyServiceReference.MyServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServicePortTypeClient : System.ServiceModel.ClientBase<HelloSoapClient.MyServiceReference.MyServicePortType>, HelloSoapClient.MyServiceReference.MyServicePortType {
        
        public MyServicePortTypeClient() {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloSoapClient.MyServiceReference.HelloWorldResponse HelloSoapClient.MyServiceReference.MyServicePortType.HelloWorld(HelloSoapClient.MyServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HelloSoapClient.MyServiceReference.HelloWorldRequest inValue = new HelloSoapClient.MyServiceReference.HelloWorldRequest();
            HelloSoapClient.MyServiceReference.HelloWorldResponse retVal = ((HelloSoapClient.MyServiceReference.MyServicePortType)(this)).HelloWorld(inValue);
            return retVal.answer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloSoapClient.MyServiceReference.HelloWorldResponse> HelloSoapClient.MyServiceReference.MyServicePortType.HelloWorldAsync(HelloSoapClient.MyServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloSoapClient.MyServiceReference.HelloWorldResponse> HelloWorldAsync() {
            HelloSoapClient.MyServiceReference.HelloWorldRequest inValue = new HelloSoapClient.MyServiceReference.HelloWorldRequest();
            return ((HelloSoapClient.MyServiceReference.MyServicePortType)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloSoapClient.MyServiceReference.GreetUserResponse HelloSoapClient.MyServiceReference.MyServicePortType.GreetUser(HelloSoapClient.MyServiceReference.GreetUserRequest request) {
            return base.Channel.GreetUser(request);
        }
        
        public string GreetUser(string name, int age) {
            HelloSoapClient.MyServiceReference.GreetUserRequest inValue = new HelloSoapClient.MyServiceReference.GreetUserRequest();
            inValue.name = name;
            inValue.age = age;
            HelloSoapClient.MyServiceReference.GreetUserResponse retVal = ((HelloSoapClient.MyServiceReference.MyServicePortType)(this)).GreetUser(inValue);
            return retVal.answer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloSoapClient.MyServiceReference.GreetUserResponse> HelloSoapClient.MyServiceReference.MyServicePortType.GreetUserAsync(HelloSoapClient.MyServiceReference.GreetUserRequest request) {
            return base.Channel.GreetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloSoapClient.MyServiceReference.GreetUserResponse> GreetUserAsync(string name, int age) {
            HelloSoapClient.MyServiceReference.GreetUserRequest inValue = new HelloSoapClient.MyServiceReference.GreetUserRequest();
            inValue.name = name;
            inValue.age = age;
            return ((HelloSoapClient.MyServiceReference.MyServicePortType)(this)).GreetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloSoapClient.MyServiceReference.GetCityInfoResponse HelloSoapClient.MyServiceReference.MyServicePortType.GetCityInfo(HelloSoapClient.MyServiceReference.GetCityInfoRequest request) {
            return base.Channel.GetCityInfo(request);
        }
        
        public HelloSoapClient.MyServiceReference.cityinfo GetCityInfo(string name) {
            HelloSoapClient.MyServiceReference.GetCityInfoRequest inValue = new HelloSoapClient.MyServiceReference.GetCityInfoRequest();
            inValue.name = name;
            HelloSoapClient.MyServiceReference.GetCityInfoResponse retVal = ((HelloSoapClient.MyServiceReference.MyServicePortType)(this)).GetCityInfo(inValue);
            return retVal.answer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloSoapClient.MyServiceReference.GetCityInfoResponse> HelloSoapClient.MyServiceReference.MyServicePortType.GetCityInfoAsync(HelloSoapClient.MyServiceReference.GetCityInfoRequest request) {
            return base.Channel.GetCityInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloSoapClient.MyServiceReference.GetCityInfoResponse> GetCityInfoAsync(string name) {
            HelloSoapClient.MyServiceReference.GetCityInfoRequest inValue = new HelloSoapClient.MyServiceReference.GetCityInfoRequest();
            inValue.name = name;
            return ((HelloSoapClient.MyServiceReference.MyServicePortType)(this)).GetCityInfoAsync(inValue);
        }
    }
}
