//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualTaskSoapDS.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ServiceReference1.MyServicePortType")]
    public interface MyServicePortType {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (CreatePerson_Request) сообщения CreatePersonRequest не соответствует значению по умолчанию (CreatePerson).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndividualTaskSoapDS.ServiceReference1.CreatePersonResponse CreatePerson(IndividualTaskSoapDS.ServiceReference1.CreatePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.CreatePersonResponse> CreatePersonAsync(IndividualTaskSoapDS.ServiceReference1.CreatePersonRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ListPeople_Request) сообщения ListPeopleRequest не соответствует значению по умолчанию (ListPeople).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndividualTaskSoapDS.ServiceReference1.ListPeopleResponse ListPeople(IndividualTaskSoapDS.ServiceReference1.ListPeopleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ListPeopleResponse> ListPeopleAsync(IndividualTaskSoapDS.ServiceReference1.ListPeopleRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ReadPerson_Request) сообщения ReadPersonRequest не соответствует значению по умолчанию (ReadPerson).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndividualTaskSoapDS.ServiceReference1.ReadPersonResponse ReadPerson(IndividualTaskSoapDS.ServiceReference1.ReadPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ReadPersonResponse> ReadPersonAsync(IndividualTaskSoapDS.ServiceReference1.ReadPersonRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (UpdatePerson_Request) сообщения UpdatePersonRequest не соответствует значению по умолчанию (UpdatePerson).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndividualTaskSoapDS.ServiceReference1.UpdatePersonResponse UpdatePerson(IndividualTaskSoapDS.ServiceReference1.UpdatePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.UpdatePersonResponse> UpdatePersonAsync(IndividualTaskSoapDS.ServiceReference1.UpdatePersonRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (DeletePerson_Request) сообщения DeletePersonRequest не соответствует значению по умолчанию (DeletePerson).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndividualTaskSoapDS.ServiceReference1.DeletePersonResponse DeletePerson(IndividualTaskSoapDS.ServiceReference1.DeletePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.DeletePersonResponse> DeletePersonAsync(IndividualTaskSoapDS.ServiceReference1.DeletePersonRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ListLanguages_Request) сообщения ListLanguagesRequest не соответствует значению по умолчанию (ListLanguages).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndividualTaskSoapDS.ServiceReference1.ListLanguagesResponse ListLanguages(IndividualTaskSoapDS.ServiceReference1.ListLanguagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ListLanguagesResponse> ListLanguagesAsync(IndividualTaskSoapDS.ServiceReference1.ListLanguagesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (CreateLanguage_Request) сообщения CreateLanguageRequest не соответствует значению по умолчанию (CreateLanguage).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndividualTaskSoapDS.ServiceReference1.CreateLanguageResponse CreateLanguage(IndividualTaskSoapDS.ServiceReference1.CreateLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.CreateLanguageResponse> CreateLanguageAsync(IndividualTaskSoapDS.ServiceReference1.CreateLanguageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ReadLanguage_Request) сообщения ReadLanguageRequest не соответствует значению по умолчанию (ReadLanguage).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndividualTaskSoapDS.ServiceReference1.ReadLanguageResponse ReadLanguage(IndividualTaskSoapDS.ServiceReference1.ReadLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ReadLanguageResponse> ReadLanguageAsync(IndividualTaskSoapDS.ServiceReference1.ReadLanguageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (UpdateLanguage_Request) сообщения UpdateLanguageRequest не соответствует значению по умолчанию (UpdateLanguage).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndividualTaskSoapDS.ServiceReference1.UpdateLanguageResponse UpdateLanguage(IndividualTaskSoapDS.ServiceReference1.UpdateLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.UpdateLanguageResponse> UpdateLanguageAsync(IndividualTaskSoapDS.ServiceReference1.UpdateLanguageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (DeleteLanguage_Request) сообщения DeleteLanguageRequest не соответствует значению по умолчанию (DeleteLanguage).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndividualTaskSoapDS.ServiceReference1.DeleteLanguageResponse DeleteLanguage(IndividualTaskSoapDS.ServiceReference1.DeleteLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.DeleteLanguageResponse> DeleteLanguageAsync(IndividualTaskSoapDS.ServiceReference1.DeleteLanguageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePerson_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class CreatePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=1)]
        public int Age;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=2)]
        public string Mail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=3)]
        public int LanguageID;
        
        public CreatePersonRequest() {
        }
        
        public CreatePersonRequest(string Name, int Age, string Mail, int LanguageID) {
            this.Name = Name;
            this.Age = Age;
            this.Mail = Mail;
            this.LanguageID = LanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePerson_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class CreatePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public CreatePersonResponse() {
        }
        
        public CreatePersonResponse(bool state) {
            this.state = state;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
    public partial class SOAP_Person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int ageField;
        
        private string mailField;
        
        private int languageIDField;
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("Mail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int LanguageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
                this.RaisePropertyChanged("LanguageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
    public partial class SOAP_Language : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPeople_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ListPeopleRequest {
        
        public ListPeopleRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPeople_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ListPeopleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Person")]
        public IndividualTaskSoapDS.ServiceReference1.SOAP_Person[] Person;
        
        public ListPeopleResponse() {
        }
        
        public ListPeopleResponse(IndividualTaskSoapDS.ServiceReference1.SOAP_Person[] Person) {
            this.Person = Person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadPerson_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ReadPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        public ReadPersonRequest() {
        }
        
        public ReadPersonRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadPerson_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ReadPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public IndividualTaskSoapDS.ServiceReference1.SOAP_Person Person;
        
        public ReadPersonResponse() {
        }
        
        public ReadPersonResponse(IndividualTaskSoapDS.ServiceReference1.SOAP_Person Person) {
            this.Person = Person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePerson_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class UpdatePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=2)]
        public int Age;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=3)]
        public string Mail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=4)]
        public int LanguageID;
        
        public UpdatePersonRequest() {
        }
        
        public UpdatePersonRequest(int ID, string Name, int Age, string Mail, int LanguageID) {
            this.ID = ID;
            this.Name = Name;
            this.Age = Age;
            this.Mail = Mail;
            this.LanguageID = LanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePerson_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class UpdatePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public UpdatePersonResponse() {
        }
        
        public UpdatePersonResponse(bool state) {
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePerson_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class DeletePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        public DeletePersonRequest() {
        }
        
        public DeletePersonRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePerson_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class DeletePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public DeletePersonResponse() {
        }
        
        public DeletePersonResponse(bool state) {
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListLanguages_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ListLanguagesRequest {
        
        public ListLanguagesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListLanguages_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ListLanguagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Language")]
        public IndividualTaskSoapDS.ServiceReference1.SOAP_Language[] Language;
        
        public ListLanguagesResponse() {
        }
        
        public ListLanguagesResponse(IndividualTaskSoapDS.ServiceReference1.SOAP_Language[] Language) {
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateLanguage_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class CreateLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string Name;
        
        public CreateLanguageRequest() {
        }
        
        public CreateLanguageRequest(string Name) {
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateLanguage_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class CreateLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public CreateLanguageResponse() {
        }
        
        public CreateLanguageResponse(bool state) {
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadLanguage_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ReadLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        public ReadLanguageRequest() {
        }
        
        public ReadLanguageRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadLanguage_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ReadLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public IndividualTaskSoapDS.ServiceReference1.SOAP_Language Language;
        
        public ReadLanguageResponse() {
        }
        
        public ReadLanguageResponse(IndividualTaskSoapDS.ServiceReference1.SOAP_Language Language) {
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateLanguage_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class UpdateLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=1)]
        public string Name;
        
        public UpdateLanguageRequest() {
        }
        
        public UpdateLanguageRequest(int ID, string Name) {
            this.ID = ID;
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateLanguage_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class UpdateLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public UpdateLanguageResponse() {
        }
        
        public UpdateLanguageResponse(bool state) {
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteLanguage_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class DeleteLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        public DeleteLanguageRequest() {
        }
        
        public DeleteLanguageRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteLanguage_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class DeleteLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public DeleteLanguageResponse() {
        }
        
        public DeleteLanguageResponse(bool state) {
            this.state = state;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServicePortTypeChannel : IndividualTaskSoapDS.ServiceReference1.MyServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServicePortTypeClient : System.ServiceModel.ClientBase<IndividualTaskSoapDS.ServiceReference1.MyServicePortType>, IndividualTaskSoapDS.ServiceReference1.MyServicePortType {
        
        public MyServicePortTypeClient() {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndividualTaskSoapDS.ServiceReference1.CreatePersonResponse IndividualTaskSoapDS.ServiceReference1.MyServicePortType.CreatePerson(IndividualTaskSoapDS.ServiceReference1.CreatePersonRequest request) {
            return base.Channel.CreatePerson(request);
        }
        
        public bool CreatePerson(string Name, int Age, string Mail, int LanguageID) {
            IndividualTaskSoapDS.ServiceReference1.CreatePersonRequest inValue = new IndividualTaskSoapDS.ServiceReference1.CreatePersonRequest();
            inValue.Name = Name;
            inValue.Age = Age;
            inValue.Mail = Mail;
            inValue.LanguageID = LanguageID;
            IndividualTaskSoapDS.ServiceReference1.CreatePersonResponse retVal = ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).CreatePerson(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.CreatePersonResponse> IndividualTaskSoapDS.ServiceReference1.MyServicePortType.CreatePersonAsync(IndividualTaskSoapDS.ServiceReference1.CreatePersonRequest request) {
            return base.Channel.CreatePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.CreatePersonResponse> CreatePersonAsync(string Name, int Age, string Mail, int LanguageID) {
            IndividualTaskSoapDS.ServiceReference1.CreatePersonRequest inValue = new IndividualTaskSoapDS.ServiceReference1.CreatePersonRequest();
            inValue.Name = Name;
            inValue.Age = Age;
            inValue.Mail = Mail;
            inValue.LanguageID = LanguageID;
            return ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).CreatePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndividualTaskSoapDS.ServiceReference1.ListPeopleResponse IndividualTaskSoapDS.ServiceReference1.MyServicePortType.ListPeople(IndividualTaskSoapDS.ServiceReference1.ListPeopleRequest request) {
            return base.Channel.ListPeople(request);
        }
        
        public IndividualTaskSoapDS.ServiceReference1.SOAP_Person[] ListPeople() {
            IndividualTaskSoapDS.ServiceReference1.ListPeopleRequest inValue = new IndividualTaskSoapDS.ServiceReference1.ListPeopleRequest();
            IndividualTaskSoapDS.ServiceReference1.ListPeopleResponse retVal = ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).ListPeople(inValue);
            return retVal.Person;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ListPeopleResponse> IndividualTaskSoapDS.ServiceReference1.MyServicePortType.ListPeopleAsync(IndividualTaskSoapDS.ServiceReference1.ListPeopleRequest request) {
            return base.Channel.ListPeopleAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ListPeopleResponse> ListPeopleAsync() {
            IndividualTaskSoapDS.ServiceReference1.ListPeopleRequest inValue = new IndividualTaskSoapDS.ServiceReference1.ListPeopleRequest();
            return ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).ListPeopleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndividualTaskSoapDS.ServiceReference1.ReadPersonResponse IndividualTaskSoapDS.ServiceReference1.MyServicePortType.ReadPerson(IndividualTaskSoapDS.ServiceReference1.ReadPersonRequest request) {
            return base.Channel.ReadPerson(request);
        }
        
        public IndividualTaskSoapDS.ServiceReference1.SOAP_Person ReadPerson(int ID) {
            IndividualTaskSoapDS.ServiceReference1.ReadPersonRequest inValue = new IndividualTaskSoapDS.ServiceReference1.ReadPersonRequest();
            inValue.ID = ID;
            IndividualTaskSoapDS.ServiceReference1.ReadPersonResponse retVal = ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).ReadPerson(inValue);
            return retVal.Person;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ReadPersonResponse> IndividualTaskSoapDS.ServiceReference1.MyServicePortType.ReadPersonAsync(IndividualTaskSoapDS.ServiceReference1.ReadPersonRequest request) {
            return base.Channel.ReadPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ReadPersonResponse> ReadPersonAsync(int ID) {
            IndividualTaskSoapDS.ServiceReference1.ReadPersonRequest inValue = new IndividualTaskSoapDS.ServiceReference1.ReadPersonRequest();
            inValue.ID = ID;
            return ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).ReadPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndividualTaskSoapDS.ServiceReference1.UpdatePersonResponse IndividualTaskSoapDS.ServiceReference1.MyServicePortType.UpdatePerson(IndividualTaskSoapDS.ServiceReference1.UpdatePersonRequest request) {
            return base.Channel.UpdatePerson(request);
        }
        
        public bool UpdatePerson(int ID, string Name, int Age, string Mail, int LanguageID) {
            IndividualTaskSoapDS.ServiceReference1.UpdatePersonRequest inValue = new IndividualTaskSoapDS.ServiceReference1.UpdatePersonRequest();
            inValue.ID = ID;
            inValue.Name = Name;
            inValue.Age = Age;
            inValue.Mail = Mail;
            inValue.LanguageID = LanguageID;
            IndividualTaskSoapDS.ServiceReference1.UpdatePersonResponse retVal = ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).UpdatePerson(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.UpdatePersonResponse> IndividualTaskSoapDS.ServiceReference1.MyServicePortType.UpdatePersonAsync(IndividualTaskSoapDS.ServiceReference1.UpdatePersonRequest request) {
            return base.Channel.UpdatePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.UpdatePersonResponse> UpdatePersonAsync(int ID, string Name, int Age, string Mail, int LanguageID) {
            IndividualTaskSoapDS.ServiceReference1.UpdatePersonRequest inValue = new IndividualTaskSoapDS.ServiceReference1.UpdatePersonRequest();
            inValue.ID = ID;
            inValue.Name = Name;
            inValue.Age = Age;
            inValue.Mail = Mail;
            inValue.LanguageID = LanguageID;
            return ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).UpdatePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndividualTaskSoapDS.ServiceReference1.DeletePersonResponse IndividualTaskSoapDS.ServiceReference1.MyServicePortType.DeletePerson(IndividualTaskSoapDS.ServiceReference1.DeletePersonRequest request) {
            return base.Channel.DeletePerson(request);
        }
        
        public bool DeletePerson(int ID) {
            IndividualTaskSoapDS.ServiceReference1.DeletePersonRequest inValue = new IndividualTaskSoapDS.ServiceReference1.DeletePersonRequest();
            inValue.ID = ID;
            IndividualTaskSoapDS.ServiceReference1.DeletePersonResponse retVal = ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).DeletePerson(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.DeletePersonResponse> IndividualTaskSoapDS.ServiceReference1.MyServicePortType.DeletePersonAsync(IndividualTaskSoapDS.ServiceReference1.DeletePersonRequest request) {
            return base.Channel.DeletePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.DeletePersonResponse> DeletePersonAsync(int ID) {
            IndividualTaskSoapDS.ServiceReference1.DeletePersonRequest inValue = new IndividualTaskSoapDS.ServiceReference1.DeletePersonRequest();
            inValue.ID = ID;
            return ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).DeletePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndividualTaskSoapDS.ServiceReference1.ListLanguagesResponse IndividualTaskSoapDS.ServiceReference1.MyServicePortType.ListLanguages(IndividualTaskSoapDS.ServiceReference1.ListLanguagesRequest request) {
            return base.Channel.ListLanguages(request);
        }
        
        public IndividualTaskSoapDS.ServiceReference1.SOAP_Language[] ListLanguages() {
            IndividualTaskSoapDS.ServiceReference1.ListLanguagesRequest inValue = new IndividualTaskSoapDS.ServiceReference1.ListLanguagesRequest();
            IndividualTaskSoapDS.ServiceReference1.ListLanguagesResponse retVal = ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).ListLanguages(inValue);
            return retVal.Language;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ListLanguagesResponse> IndividualTaskSoapDS.ServiceReference1.MyServicePortType.ListLanguagesAsync(IndividualTaskSoapDS.ServiceReference1.ListLanguagesRequest request) {
            return base.Channel.ListLanguagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ListLanguagesResponse> ListLanguagesAsync() {
            IndividualTaskSoapDS.ServiceReference1.ListLanguagesRequest inValue = new IndividualTaskSoapDS.ServiceReference1.ListLanguagesRequest();
            return ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).ListLanguagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndividualTaskSoapDS.ServiceReference1.CreateLanguageResponse IndividualTaskSoapDS.ServiceReference1.MyServicePortType.CreateLanguage(IndividualTaskSoapDS.ServiceReference1.CreateLanguageRequest request) {
            return base.Channel.CreateLanguage(request);
        }
        
        public bool CreateLanguage(string Name) {
            IndividualTaskSoapDS.ServiceReference1.CreateLanguageRequest inValue = new IndividualTaskSoapDS.ServiceReference1.CreateLanguageRequest();
            inValue.Name = Name;
            IndividualTaskSoapDS.ServiceReference1.CreateLanguageResponse retVal = ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).CreateLanguage(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.CreateLanguageResponse> IndividualTaskSoapDS.ServiceReference1.MyServicePortType.CreateLanguageAsync(IndividualTaskSoapDS.ServiceReference1.CreateLanguageRequest request) {
            return base.Channel.CreateLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.CreateLanguageResponse> CreateLanguageAsync(string Name) {
            IndividualTaskSoapDS.ServiceReference1.CreateLanguageRequest inValue = new IndividualTaskSoapDS.ServiceReference1.CreateLanguageRequest();
            inValue.Name = Name;
            return ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).CreateLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndividualTaskSoapDS.ServiceReference1.ReadLanguageResponse IndividualTaskSoapDS.ServiceReference1.MyServicePortType.ReadLanguage(IndividualTaskSoapDS.ServiceReference1.ReadLanguageRequest request) {
            return base.Channel.ReadLanguage(request);
        }
        
        public IndividualTaskSoapDS.ServiceReference1.SOAP_Language ReadLanguage(int ID) {
            IndividualTaskSoapDS.ServiceReference1.ReadLanguageRequest inValue = new IndividualTaskSoapDS.ServiceReference1.ReadLanguageRequest();
            inValue.ID = ID;
            IndividualTaskSoapDS.ServiceReference1.ReadLanguageResponse retVal = ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).ReadLanguage(inValue);
            return retVal.Language;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ReadLanguageResponse> IndividualTaskSoapDS.ServiceReference1.MyServicePortType.ReadLanguageAsync(IndividualTaskSoapDS.ServiceReference1.ReadLanguageRequest request) {
            return base.Channel.ReadLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.ReadLanguageResponse> ReadLanguageAsync(int ID) {
            IndividualTaskSoapDS.ServiceReference1.ReadLanguageRequest inValue = new IndividualTaskSoapDS.ServiceReference1.ReadLanguageRequest();
            inValue.ID = ID;
            return ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).ReadLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndividualTaskSoapDS.ServiceReference1.UpdateLanguageResponse IndividualTaskSoapDS.ServiceReference1.MyServicePortType.UpdateLanguage(IndividualTaskSoapDS.ServiceReference1.UpdateLanguageRequest request) {
            return base.Channel.UpdateLanguage(request);
        }
        
        public bool UpdateLanguage(int ID, string Name) {
            IndividualTaskSoapDS.ServiceReference1.UpdateLanguageRequest inValue = new IndividualTaskSoapDS.ServiceReference1.UpdateLanguageRequest();
            inValue.ID = ID;
            inValue.Name = Name;
            IndividualTaskSoapDS.ServiceReference1.UpdateLanguageResponse retVal = ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).UpdateLanguage(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.UpdateLanguageResponse> IndividualTaskSoapDS.ServiceReference1.MyServicePortType.UpdateLanguageAsync(IndividualTaskSoapDS.ServiceReference1.UpdateLanguageRequest request) {
            return base.Channel.UpdateLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.UpdateLanguageResponse> UpdateLanguageAsync(int ID, string Name) {
            IndividualTaskSoapDS.ServiceReference1.UpdateLanguageRequest inValue = new IndividualTaskSoapDS.ServiceReference1.UpdateLanguageRequest();
            inValue.ID = ID;
            inValue.Name = Name;
            return ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).UpdateLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndividualTaskSoapDS.ServiceReference1.DeleteLanguageResponse IndividualTaskSoapDS.ServiceReference1.MyServicePortType.DeleteLanguage(IndividualTaskSoapDS.ServiceReference1.DeleteLanguageRequest request) {
            return base.Channel.DeleteLanguage(request);
        }
        
        public bool DeleteLanguage(int ID) {
            IndividualTaskSoapDS.ServiceReference1.DeleteLanguageRequest inValue = new IndividualTaskSoapDS.ServiceReference1.DeleteLanguageRequest();
            inValue.ID = ID;
            IndividualTaskSoapDS.ServiceReference1.DeleteLanguageResponse retVal = ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).DeleteLanguage(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.DeleteLanguageResponse> IndividualTaskSoapDS.ServiceReference1.MyServicePortType.DeleteLanguageAsync(IndividualTaskSoapDS.ServiceReference1.DeleteLanguageRequest request) {
            return base.Channel.DeleteLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndividualTaskSoapDS.ServiceReference1.DeleteLanguageResponse> DeleteLanguageAsync(int ID) {
            IndividualTaskSoapDS.ServiceReference1.DeleteLanguageRequest inValue = new IndividualTaskSoapDS.ServiceReference1.DeleteLanguageRequest();
            inValue.ID = ID;
            return ((IndividualTaskSoapDS.ServiceReference1.MyServicePortType)(this)).DeleteLanguageAsync(inValue);
        }
    }
}
